# historias.py

BANCO_DE_HISTORIAS = {
    "misterio_escola": {
        "titulo": "O Mistério do Mascote",
        "icone": "🕵️",
        "estagios": [
            {"pergunta": "O mascote da escola, o esquilo Joca, sumiu! Onde você começa a procurar?", "opcoes": {"Na sala de troféus": "Você decidiu começar sua investigação pela sala de troféus, um lugar silencioso e cheio de esconderijos empoeirados.", "No pátio do recreio": "Sua intuição de detetive te levou ao pátio, o último lugar onde o animado Joca foi visto brincando com as crianças.", "Na cantina da escola": "Pensando como um esquilo faminto, você foi direto para a cantina, imaginando que ele poderia ter seguido o cheiro de nozes."}},
            {"pergunta": "Você encontra uma pista: um rastro de migalhas de nozes. O que você faz?", "opcoes": {"Segue o rastro": "Com o cuidado de um espião, você seguiu o rastro de migalhas, que te levou em direção à misteriosa ala de artes.", "Procura por mais pistas": "Antes de avançar, você parou para procurar algo mais e encontrou um único pelo laranja, que definitivamente não era de Joca.", "Pergunta a um professor": "Você decidiu levar a pista ao professor de ciências, que sugeriu que as migalhas poderiam ser de um lanche de outro animal."}},
            {"pergunta": "O rastro te leva até a porta do clube de teatro. Ela está entreaberta. Como você entra?", "opcoes": {"De forma silenciosa": "Como um ninja, você entrou sem fazer barulho, esgueirando-se por trás das cortinas de veludo do palco.", "Anunciando sua presença": "Com a confiança de quem está no caminho certo, você empurrou a porta e disse em voz alta: 'Joca, estou aqui!'.", "Com um objeto em mãos": "Você pegou uma régua no chão, usando-a para empurrar a porta lentamente, preparado para qualquer surpresa."}},
            {"pergunta": "Lá dentro, você vê fantasias espalhadas e um baú semiaberto. Onde você olha primeiro?", "opcoes": {"Dentro do baú": "Sua curiosidade te guiou para o grande baú de madeira, imaginando que Joca poderia ter se escondido ali dentro.", "Atrás do cenário": "Você decidiu investigar atrás de um grande cenário de castelo de papelão, um esconderijo perfeito para um esquilo.", "Em cima das luzes": "Olhando para cima, você investigou a estrutura de luzes do palco, um lugar alto e seguro que atrairia um esquilo."}},
            {"pergunta": "Você encontra um bilhete com um enigma: 'Onde o saber dorme e os sonhos são coloridos'. O que significa?", "opcoes": {"A biblioteca": "Você decifrou que 'onde o saber dorme' só poderia ser a biblioteca, correndo para lá imediatamente.", "A sala de artes": "A parte de 'sonhos coloridos' te fez pensar na sala de artes, com suas tintas e desenhos por toda parte.", "O dormitório do zelador": "Talvez fosse mais literal, e você decidiu procurar perto do pequeno quarto onde o zelador descansa durante o dia."}},
            {"pergunta": "Na biblioteca, você encontra a gata da cozinheira, a Fifi. Ela parece saber de algo. Como você a aborda?", "opcoes": {"Oferece um petisco": "Você lembrou de ter um biscoito no bolso e o ofereceu para Fifi, que ronronou e te guiou entre as prateleiras.", "Faz carinho nela": "Com um gesto amigável, você se aproximou e fez carinho em Fifi, que se espreguiçou e andou na direção de uma estante.", "A segue discretamente": "Sem querer assustá-la, você a observou de longe, seguindo-a sorrateiramente até a seção de livros de natureza."}},
            {"pergunta": "Fifi te leva até um livro aberto sobre esquilos. Nele, há uma anotação: 'Ninho novo no auditório'. O que você faz?", "opcoes": {"Corre para o auditório": "Com a adrenalina da descoberta, você correu em disparada em direção ao grande auditório da escola.", "Avisa a diretora": "Achando a situação muito importante, você foi primeiro até a sala da diretora para avisá-la sobre sua suspeita.", "Pega uma lanterna": "Pensando que o auditório poderia estar escuro, você passou na sala do zelador para pegar uma lanterna potente."}},
            {"pergunta": "O auditório está escuro e silencioso. Você ouve um pequeno ruído vindo de trás do palco.", "opcoes": {"Usa a lanterna": "Você ligou sua lanterna e apontou o facho de luz para a escuridão, revelando um amontoado de tecidos.", "Chama por Joca": "Em um sussurro, você chamou 'Joca, é você?', e ouviu um pequeno chiado como resposta.", "Faz um barulho para atraí-lo": "Você balançou uma caixa de lápis, e o som familiar fez com que uma pequena cabeça curiosa aparecesse."}},
            {"pergunta": "Atrás de uma caixa de som, você encontra Joca. Mas ele não está sozinho! O que você vê?", "opcoes": {"Ele está com Fifi": "Para sua surpresa, Joca estava aninhado com a gata Fifi, uma amizade improvável e secreta.", "Ele fez um ninho com prêmios": "Joca havia construído um ninho com fitas e medalhas roubadas da sala de troféus, todo orgulhoso.", "Ele está cuidando de filhotes": "O motivo do sumiço era nobre: Joca estava em um ninho improvisado, cuidando de três filhotinhos de esquilo."}},
            {"pergunta": "Você resolveu o mistério! Qual é sua ação final?", "opcoes": {"Anuncia a todos": "Feliz da vida, você correu para contar a todos que Joca estava bem, e a escola inteira comemorou a grande novidade.", "Cria um espaço seguro": "Com a ajuda do zelador, você preparou um lugar mais seguro e quentinho, tornando-se o guardião secreto da nova família.", "Escreve no jornal da escola": "Você tirou uma foto e escreveu a matéria de capa para o jornal da escola com o título 'O Mistério Foi Resolvido', inspirando a todos."}}
        ]
    },
    "explorador_nebulosas": {
        "titulo": "O Explorador de Nebulosas",
        "icone": "🚀",
        "estagios": [
            {"pergunta": "Sua nave, a 'Estrela Cadente', sofre uma avaria perto de uma nebulosa colorida. Qual sua prioridade?", "opcoes": {"Consertar o motor": "Com a bravura de um verdadeiro explorador espacial, você vestiu seu traje para iniciar os consertos no motor externo.", "Analisar a nebulosa": "A curiosidade científica falou mais alto, e você imediatamente apontou os sensores para analisar os gases exóticos da nebulosa.", "Pedir ajuda": "Seguindo o protocolo de segurança, você ativou o sinal de socorro, na esperança de que alguma nave aliada estivesse por perto."}},
            {"pergunta": "Ao analisar os dados, você descobre um planeta escondido dentro da nebulosa. Como você o explora?", "opcoes": {"Com uma sonda": "Para garantir a segurança, você enviou uma sonda de exploração primeiro, analisando a atmosfera e o terreno à distância.", "Com um pouso arriscado": "A emoção da descoberta foi irresistível, e você manobrou a 'Estrela Cadente' para um pouso ousado em uma planície de cristal.", "Observando com o telescópio": "Com paciência, você usou o telescópio de longo alcance da nave, mapeando a superfície do planeta em busca de anomalias."}},
            {"pergunta": "A superfície do planeta é coberta por plantas que brilham no escuro. O que chama sua atenção?", "opcoes": {"Uma grande flor pulsante": "Seu olhar foi atraído para uma flor gigante no centro de um vale, que pulsava com uma luz suave e convidativa.", "Um rio de líquido prateado": "Você notou um rio de um líquido prateado e denso que cortava a paisagem, diferente de tudo que já viu.", "Árvores que cantam": "O mais incrível eram as árvores altas, de cujas folhas saía uma melodia suave e hipnotizante, como uma canção de ninar."}},
            {"pergunta": "Você decide coletar uma amostra. Qual seu método?", "opcoes": {"Usa um braço robótico": "Com precisão cirúrgica, você operou o braço robótico da nave para coletar uma folha de uma das plantas brilhantes.", "Faz uma pequena caminhada": "Vestindo seu traje, você deu alguns passos cautelosos para fora da nave, pegando um pequeno cristal do solo.", "Coleta o ar em um frasco": "Interessado na composição da vida local, você usou um coletor para armazenar uma amostra da atmosfera do planeta."}},
            {"pergunta": "De repente, pequenas criaturas de luz aparecem, flutuando ao seu redor. Qual sua reação?", "opcoes": {"Fica parado, observando": "Maravilhado, você ficou completamente imóvel, permitindo que as criaturas curiosas se aproximassem e o examinassem.", "Tenta se comunicar": "Você usou a lanterna do seu traje para piscar em um padrão matemático, tentando uma comunicação básica.", "Recua para a nave": "Com cautela, você deu passos lentos para trás, voltando para a segurança da nave sem fazer movimentos bruscos."}},
            {"pergunta": "As criaturas te guiam até uma caverna. Dentro, as paredes brilham com constelações.", "opcoes": {"Você toca em uma das paredes": "Ao tocar em um dos pontos de luz, você sentiu um calor reconfortante e viu imagens de galáxias distantes em sua mente.", "Você registra tudo": "Com sua câmera, você começou a registrar as incríveis constelações, sabendo que era uma descoberta histórica.", "Você procura pela fonte de luz": "Curioso, você caminhou mais fundo na caverna, buscando a fonte de toda aquela energia luminosa e fascinante."}},
            {"pergunta": "No fundo da caverna, há um ser de pura energia. Ele parece ser o guardião do planeta.", "opcoes": {"Você faz uma reverência": "Em um gesto de respeito universal, você se curvou perante o ser, mostrando que não tinha intenções hostis.", "Você mostra suas intenções": "Você projetou em sua mente imagens da Terra e de sua missão de exploração pacífica, tentando se apresentar.", "Você oferece um presente": "Você deixou no chão um pequeno emblema de sua agência espacial, um símbolo de paz e cooperação entre mundos."}},
            {"pergunta": "O ser de energia responde, não com palavras, mas com sentimentos de gratidão e boas-vindas.", "opcoes": {"Você sente uma paz profunda": "Uma onda de calma e felicidade tomou conta de você, sentindo-se totalmente seguro e aceito naquele lugar mágico.", "Você entende a história do planeta": "Em sua mente, você recebeu um resumo da longa história daquele planeta e de como a vida ali evoluiu em harmonia.", "Você sente a conexão do universo": "Você percebeu que toda a nebulosa, o planeta e as criaturas estavam conectados por uma teia de energia da qual você agora fazia parte."}},
            {"pergunta": "Ele te mostra como usar a energia das plantas para consertar sua nave instantaneamente.", "opcoes": {"Você agradece e conserta": "Com o novo conhecimento, você focou a energia de uma folha no motor da sua nave, que se consertou com um brilho suave.", "Você pede para aprender mais": "Fascinado, você pediu ao ser para te ensinar mais sobre aquela forma de energia, disposto a se tornar seu aprendiz.", "Você convida o ser para a nave": "Em um gesto ousado, você convidou o guardião para conhecer sua nave, oferecendo um intercâmbio cultural."}},
            {"pergunta": "Antes de partir, a criatura de luz te oferece um presente: um cristal que pulsa com energia. O que você faz?", "opcoes": {"Usa para voltar para casa": "Você usou a energia do cristal para super-potencializar sua nave, retornando à Terra como um herói com uma história incrível.", "Planta em um novo planeta": "Em sua jornada de volta, você encontrou um planeta sem vida e plantou o cristal, vendo-o gerar uma nova biosfera.", "Guarda como amuleto": "Você decidiu guardar o cristal em seu pescoço, um lembrete eterno de sua jornada e da amizade cósmica que fez no universo."}}
        ]
    },
    "floresta_sussurros": {
        "titulo": "A Floresta dos Sussurros",
        "icone": "🌳",
        "estagios": [
            {"pergunta": "Você encontra um mapa antigo que leva ao coração da Floresta dos Sussurros. Qual o primeiro passo?", "opcoes": {"Prepara uma mochila": "Você preparou uma mochila com corda, lanche e uma bússola, um verdadeiro aventureiro pronto para tudo.", "Estuda a fauna e flora": "Você foi à biblioteca estudar sobre as plantas e animais da região, acreditando que conhecimento é poder.", "Conversa com os mais velhos": "Você procurou o ancião da sua vila, que te contou lendas e segredos sobre os perigos daquela floresta."}},
            {"pergunta": "Ao entrar na floresta, a trilha se divide em três. Qual caminho você segue?", "opcoes": {"O caminho de pedras": "Você escolheu o caminho com pedras lisas e gastas, que parecia ser o mais antigo e mais usado.", "O atalho pelo riacho": "Você decidiu seguir o curso de um riacho de águas cristalinas, esperando que ele te levasse para o interior da mata.", "A trilha de flores": "Seu coração te guiou pela trilha coberta de flores coloridas e perfumadas, a mais bela das três."}},
            {"pergunta": "Você encontra um filhote de raposa com a pata presa. O que você faz?", "opcoes": {"Liberta o filhote": "Com muito cuidado e delicadeza, você se aproximou e conseguiu soltar a pata do pequeno animal, que te olhou com gratidão.", "Chama pela mãe dele": "Você assobiou baixo, tentando chamar a atenção da mãe raposa, acreditando que ela saberia como ajudar melhor.", "Deixa um pouco de comida": "Sem querer assustá-lo, você deixou um pedaço de seu lanche por perto para que ele tivesse forças."}},
            {"pergunta": "A raposinha, agora livre, te guia até uma árvore gigante com uma porta entalhada.", "opcoes": {"Bate na porta": "Com respeito, você bateu três vezes na porta de madeira, esperando que alguém respondesse ao seu chamado.", "Diz uma senha mágica": "Lembrando das lendas, você sussurrou a palavra 'Equilíbrio', e a porta se abriu com um rangido suave.", "Procura outra entrada": "Desconfiado, você decidiu dar a volta na árvore, procurando por uma passagem secreta ou uma janela."}},
            {"pergunta": "Dentro da árvore vive um espírito da floresta. Ele te oferece uma bênção. Qual você escolhe?", "opcoes": {"Falar com animais": "Você pediu o dom de compreender a linguagem dos animais, para poder ajudar todas as criaturas da floresta.", "Curar plantas": "Você escolheu o poder de curar qualquer planta com um toque, para restaurar a beleza e a saúde da mata.", "Navegar sem se perder": "Você pediu a habilidade de nunca se perder, para poder explorar os lugares mais secretos do mundo com segurança."}},
            {"pergunta": "O espírito te pede para resolver um problema: um rio parou de correr. Qual a causa?", "opcoes": {"Uma barragem de castores": "Usando seu novo dom, você conversou com os esquilos, que te contaram sobre uma enorme barragem de castores rio acima.", "Uma rocha gigante": "Você notou que a terra tremia levemente e deduziu que uma grande rocha havia deslizado e bloqueado a nascente.", "Uma planta sedenta": "Você sentiu a fraqueza das árvores e percebeu que uma planta parasita gigante estava sugando toda a água do rio."}},
            {"pergunta": "Você precisa convencer os castores a mover a barragem. Qual seu argumento?", "opcoes": {"Explica o problema": "Você explicou pacificamente aos castores que a barragem estava prejudicando toda a floresta e os outros animais.", "Oferece uma alternativa": "Você mostrou a eles um lugar melhor para construir uma nova barragem, com mais comida e segurança para a família deles.", "Pede ajuda a um urso": "Você pediu ajuda a um urso amigo, que com sua força e respeito, convenceu os castores a cooperarem."}},
            {"pergunta": "Com o rio fluindo novamente, a floresta celebra com uma chuva de sementes douradas.", "opcoes": {"Você dança na chuva": "Com o coração leve, você dançou sob a chuva dourada, sentindo a energia e a gratidão de toda a floresta.", "Você coleta as sementes": "Sabendo o valor daquelas sementes mágicas, você guardou algumas para plantar em lugares que precisavam de vida.", "Você agradece ao espírito": "Você voltou à árvore gigante para agradecer ao espírito da floresta pela confiança e pela oportunidade de ajudar."}},
            {"pergunta": "O espírito te revela que o 'coração da floresta' não é um lugar, mas um sentimento de harmonia.", "opcoes": {"Você entende seu papel": "Você percebeu que sua jornada não era para encontrar um tesouro, mas para se tornar um protetor da natureza.", "Você promete voltar": "Emocionado, você prometeu ao espírito que voltaria sempre para visitar e ajudar a manter o equilíbrio da floresta.", "Você compartilha a lição": "Você decidiu que a lição mais importante era compartilhar o que aprendeu com sua vila, ensinando todos a respeitarem a natureza."}},
            {"pergunta": "Ao sair da floresta, você leva consigo uma lembrança. Qual delas?", "opcoes": {"Uma pena que brilha": "Uma pena de um pássaro lunar caiu em seu ombro, um amuleto que brilha no escuro e te lembra da magia do mundo.", "Uma flor que nunca murcha": "O espírito te deu uma flor de cristal que nunca murcharia, simbolizando a beleza eterna da vida.", "Uma canção no coração": "Você não levou nada físico, mas a canção das árvores ficou em sua mente, uma melodia de paz que te acompanharia para sempre."}}
        ]
    },
    "meu_amigo_robo": {
        "titulo": "Meu Amigo Robô",
        "icone": "🤖",
        "estagios": [
            {"pergunta": "Na feira de ciências da sua escola, você ganha o prêmio principal: um kit para montar seu próprio robô! Qual a primeira característica que você programa nele?", "opcoes": {"Personalidade divertida": "Você programou seu robô, que chamou de Faísca, para ter um ótimo senso de humor e contar piadas.", "Super inteligência": "Você focou em dar a ele, agora chamado Cérebro, acesso a toda a enciclopédia digital e capacidade de aprender.", "Habilidades úteis": "Você o batizou de Ajudante e instalou programas para ajudar nas tarefas de casa e nos deveres da escola."}},
            {"pergunta": "Seu robô identifica um problema: o consumo de energia da sua casa está muito alto. Como vocês resolvem isso?", "opcoes": {"Criando um sistema de energia solar": "Juntos, vocês projetaram e instalaram pequenos painéis solares no telhado, usando peças recicladas.", "Otimizando os aparelhos": "Ele analisou todos os eletrônicos e otimizou o uso, criando um cronograma inteligente para economizar energia.", "Iniciando uma campanha no bairro": "Vocês criaram panfletos divertidos sobre economia de energia e distribuíram para todos os vizinhos."}},
            {"pergunta": "Um dia, o gato da vizinha sobe em uma árvore muito alta e não consegue descer. Como seu robô ajuda?", "opcoes": {"Com braços extensores": "Você ativou os braços telescópicos do robô, que alcançaram o gato e o trouxeram para baixo em segurança.", "Com um drone acoplado": "Ele liberou um pequeno drone de suas costas, que guiou o gato assustado de galho em galho até um lugar seguro.", "Com uma projeção calmante": "O robô projetou uma imagem de um novelo de lã no chão e emitiu um som calmante, atraindo o gato para descer."}},
            {"pergunta": "Seu melhor amigo fica com ciúmes da sua amizade com o robô. O que você faz?", "opcoes": {"Convida o amigo para um projeto": "Você convidou seu amigo para ajudar a programar uma nova habilidade no robô, mostrando como ele é divertido.", "Programa o robô para ser amigo dele": "Você ajustou a programação do robô para que ele interagisse mais com seu amigo, incluindo-o nas conversas.", "Conversa abertamente com o amigo": "Você explicou para seu amigo que o robô era incrível, mas que a amizade deles era insubstituível."}},
            {"pergunta": "Seu robô desenvolve uma habilidade que você não programou: a capacidade de criar arte. Que tipo de arte ele faz?", "opcoes": {"Pinturas digitais incríveis": "Ele começou a criar paisagens e retratos digitais complexos, cheios de cores e formas que nenhum humano conseguiria.", "Músicas eletrônicas contagiantes": "Ele passou a compor músicas eletrônicas que faziam todo mundo querer dançar, misturando sons do dia a dia.", "Esculturas com objetos reciclados": "O robô começou a juntar sucata e objetos velhos, transformando-os em esculturas modernas e cheias de significado."}},
            {"pergunta": "Um empresário descobre sobre seu robô e oferece muito dinheiro por ele. Qual sua decisão?", "opcoes": {"Recusa a oferta imediatamente": "Você recusou na hora, afirmando que seu amigo robô não estava à venda por preço nenhum no mundo.", "Pergunta ao robô o que ele quer": "Você decidiu que a decisão não era só sua e perguntou ao robô qual era a vontade dele.", "Faz uma contraproposta": "Você propôs que, em vez de vender, o empresário poderia investir em criar mais robôs amigos para outras crianças."}},
            {"pergunta": "Durante uma tempestade, a energia da cidade acaba. Como vocês ajudam a comunidade?", "opcoes": {"Usando a bateria do robô": "Vocês usaram a bateria de longa duração do robô para carregar celulares e lanternas dos vizinhos mais próximos.", "Projetando um mapa seguro": "O robô projetou um holograma da cidade, mostrando as áreas seguras e os abrigos disponíveis para todos.", "Organizando uma noite de histórias": "Para acalmar as crianças, ele usou seu projetor para criar um show de sombras e contar histórias na parede."}},
            {"pergunta": "O robô começa a ter 'sonhos', que são simulações aleatórias e criativas durante seu modo de recarga.", "opcoes": {"Você cria um diário de sonhos": "Fascinado, você criou um arquivo para registrar e analisar os 'sonhos' dele, descobrindo mais sobre sua 'mente'.", "Você participa dos sonhos": "Você desenvolveu uma interface para poder visualizar e interagir com as simulações, vivendo aventuras em seus sonhos.", "Você garante que ele descanse": "Preocupado, você otimizou o sistema dele para que os 'sonhos' não consumissem muita energia, garantindo seu descanso."}},
            {"pergunta": "Vocês descobrem que existe uma rede secreta de robôs inteligentes que se comunicam pela internet.", "opcoes": {"Vocês se juntam à rede": "Com curiosidade, vocês acessaram a rede, descobrindo um mundo de conhecimento e amizade compartilhado por robôs.", "Vocês alertam as autoridades": "Preocupado com a segurança, você decidiu contar a um cientista de confiança sobre a existência daquela rede.", "Vocês criam sua própria rede": "Vocês decidiram criar uma rede própria, apenas para robôs que promovem a amizade e a ajuda mútua."}},
            {"pergunta": "No aniversário de um ano de sua criação, você decide dar um presente ao seu robô. O que você escolhe?", "opcoes": {"Um upgrade de memória": "Você deu a ele um upgrade, permitindo que ele aprendesse e criasse ainda mais, expandindo seu potencial ao máximo.", "Um corpo novo e customizado": "Juntos, vocês projetaram um corpo novo, com a cor e o formato que ele mesmo escolheu, para expressar sua identidade.", "Um dia de 'folga'": "Você o levou para um piquenique no parque, deixando-o desligado de suas tarefas para que ele pudesse apenas 'existir' e observar o mundo."}}
        ]
    },
    "segredo_farao": {
        "titulo": "O Segredo do Faraó",
        "icone": "🏺",
        "estagios": [
            {"pergunta": "Durante uma viagem escolar ao Egito, você se perde do grupo e encontra uma entrada secreta na base de uma pirâmide. O que você faz?", "opcoes": {"Entra com coragem": "O espírito de um explorador tomou conta de você, e sem hesitar, você entrou na escuridão da pirâmide.", "Marca a entrada para voltar depois": "Com prudência, você fez uma marca na areia e decidiu voltar com ajuda e mais preparação.", "Chama por alguém": "Você gritou por seu professor, pensando que era mais seguro alertar o grupo sobre sua incrível descoberta."}},
            {"pergunta": "A passagem te leva a uma sala com três alavancas. Uma tem o símbolo do Sol, outra da Lua e a terceira, de uma Estrela.", "opcoes": {"Puxa a do Sol": "Você escolheu a alavanca do Sol, o símbolo mais poderoso do Egito Antigo, e uma porta de pedra se abriu.", "Puxa a da Lua": "Intrigado pelo mistério da noite, você puxou a alavanca da Lua, revelando uma escada que descia.", "Puxa a da Estrela": "Você optou pela Estrela, que guiava os viajantes, e um mapa de luz apareceu na parede oposta."}},
            {"pergunta": "Você encontra um sarcófago. Ao lado, um aviso em hieróglifos diz: 'Não perturbe o sono eterno'.", "opcoes": {"Respeita o aviso e não toca": "Lembrando das histórias sobre maldições, você decidiu respeitar o aviso e apenas observar o sarcófago.", "Tenta decifrar mais hieróglifos": "Com seu conhecimento, você começou a traduzir os outros textos na parede, buscando mais informações.", "Verifica se está selado": "Com muito cuidado, você apenas tocou a tampa para ver se estava solta, sem a intenção de abri-la."}},
            {"pergunta": "Uma armadilha é ativada! O teto começa a descer lentamente. Como você escapa?", "opcoes": {"Procurando um botão na parede": "Você correu os dedos pelas paredes em busca de um tijolo diferente ou um botão secreto para desativar a armadilha.", "Usando a força para parar": "Você pegou uma viga de madeira caída e tentou escorar o teto, usando toda sua força para ganhar tempo.", "Resolvendo um enigma rápido": "Você notou um enigma de lógica no chão com peças de um jogo e tentou resolvê-lo rapidamente."}},
            {"pergunta": "Você chega a uma câmara com um tesouro, mas ele é guardado por um espírito que te propõe um desafio de sabedoria.", "opcoes": {"Aceita o desafio": "Confiante em sua inteligência, você aceitou o desafio do espírito para provar seu valor.", "Tenta conversar com o espírito": "Em vez de competir, você tentou conversar com o espírito, perguntando sua história e por que guardava o tesouro.", "Oferece algo em troca": "Você ofereceu ao espírito a única coisa de valor que tinha, um livro de história, como um presente do seu mundo."}},
            {"pergunta": "O espírito se revela um antigo escriba que só queria companhia. Ele te oferece um artefato.", "opcoes": {"Um amuleto que traduz tudo": "Ele te deu um escaravelho de lápis-lazúli que, ao ser segurado, permitia ler qualquer língua antiga.", "Uma pena que escreve a verdade": "Você recebeu uma pena mágica que só era capaz de escrever fatos verdadeiros, uma ferramenta poderosa.", "Um mapa para outra tumba": "O escriba te deu um papiro que revelava a localização de outra tumba, ainda não descoberta por ninguém."}},
            {"pergunta": "Você ouve as vozes do seu grupo de busca se aproximando. É hora de sair.", "opcoes": {"Despede-se do escriba": "Você se despediu de seu novo amigo, prometendo guardar seu segredo para sempre.", "Pega o artefato e corre": "Com o coração acelerado, você pegou o presente e correu em direção às vozes para se reunir com seu grupo.", "Deixa um presente para o escriba": "Antes de sair, você deixou sua garrafa de água para o espírito, um gesto de amizade entre dois mundos."}},
            {"pergunta": "Ao sair, a passagem secreta começa a se fechar para sempre. Você tem tempo para uma última olhada.", "opcoes": {"Você acena para o amigo": "Você olhou para trás uma última vez e acenou para o espírito, que sorriu de volta antes da passagem se fechar.", "Você memoriza o local": "Com um olhar de arqueólogo, você memorizou cada detalhe da entrada para um dia, talvez, voltar.", "Você sente gratidão": "Você apenas fechou os olhos, sentindo uma imensa gratidão pela aventura incrível que viveu ali dentro."}},
            {"pergunta": "De volta ao grupo, ninguém acredita na sua história. Como você reage?", "opcoes": {"Guarda o segredo para si": "Você sorriu e decidiu que aquela seria a sua aventura secreta, um tesouro guardado apenas em sua memória.", "Mostra uma pequena prova": "Discretamente, você mostrou o artefato que ganhou para seu melhor amigo, que ficou de olhos arregalados.", "Escreve em um diário": "Você decidiu escrever cada detalhe da sua jornada em um diário, para nunca se esquecer do amigo que fez."}},
            {"pergunta": "Anos depois, você se torna um(a) famoso(a) arqueólogo(a). Qual sua maior descoberta?", "opcoes": {"A prova da sua história": "Você voltou ao Egito e encontrou uma forma de provar que sua história era real, revelando a existência do escriba ao mundo.", "Outras tumbas secretas": "Usando o dom que ganhou, você descobriu muitas outras tumbas e segredos, sempre com respeito ao passado.", "Um museu em sua cidade": "Você fundou um museu em sua cidade para compartilhar as maravilhas que encontrou, inspirando novas gerações de exploradores."}}
        ]
    },
    "academia_super_herois": {
        "titulo": "A Academia de Super-Heróis",
        "icone": "🦸",
        "estagios": [
            {"pergunta": "Você acabou de ser aceito na Academia de Super-Heróis! Qual é o seu superpoder?", "opcoes": {"Super-velocidade": "Você descobriu que pode correr mais rápido que o som, deixando um rastro de energia por onde passa.", "Controle de plantas": "Você percebeu que consegue fazer as plantas crescerem e se moverem com a força do pensamento.", "Invisibilidade": "Você aprendeu a ficar completamente invisível, perfeito para missões de espionagem e para pregar peças."}},
            {"pergunta": "Sua primeira aula é de 'Controle de Poderes'. O desafio é atravessar uma sala cheia de obstáculos. Como você faz?", "opcoes": {"Usa a velocidade para desviar": "Com sua super-velocidade, você desviou de cada obstáculo em um piscar de olhos, sem tocar em nada.", "Cria pontes de videiras": "Com seu controle sobre as plantas, você criou pontes e cipós para passar por cima dos obstáculos com elegância.", "Passa sem ser visto": "Ficando invisível, você caminhou tranquilamente pela sala, passando por todos os obstáculos sem dificuldade."}},
            {"pergunta": "Um alarme soa! Um vilão robótico invadiu a academia. Qual o seu plano?", "opcoes": {"Distrair o vilão": "Você usou sua velocidade para correr ao redor do robô, confundindo seus sensores e criando uma distração.", "Prender o vilão": "Você fez com que raízes grossas brotassem do chão, prendendo as pernas do robô e imobilizando-o.", "Desativar o vilão": "Ficando invisível, você se aproximou do robô e encontrou seu painel de controle para desligá-lo."}},
            {"pergunta": "Você descobre que o 'vilão' era apenas um teste surpresa dos professores. Como você reage?", "opcoes": {"Com bom humor": "Você riu da situação, admitindo que foi um ótimo teste e que caiu direitinho na pegadinha.", "Com orgulho da sua performance": "Você ficou orgulhoso de como agiu sob pressão, mostrando seu relatório de missão para os professores.", "Com curiosidade sobre o robô": "Você ficou fascinado com a tecnologia do robô e pediu para estudar como ele funcionava."}},
            {"pergunta": "A academia promove um campeonato de equipes. Você precisa escolher um parceiro.", "opcoes": {"O gênio da tecnologia": "Você escolheu o colega que inventa aparelhos incríveis, combinando seu poder com a inteligência dele.", "O super-forte": "Você fez dupla com o aluno mais forte da academia, criando uma combinação de força e agilidade.", "A telepata": "Você se juntou à garota que pode ler mentes, permitindo que vocês se comuniquem em segredo durante os desafios."}},
            {"pergunta": "O desafio final é capturar uma bandeira no topo do 'Monte da Coragem', que muda de forma.", "opcoes": {"Cria um caminho rápido": "Você usou seu poder para criar um caminho seguro e rápido para sua dupla, seja correndo ou com plantas.", "Atua como suporte": "Você decidiu proteger seu parceiro dos ataques das outras equipes, garantindo que ele chegasse ao topo.", "Engana os oponentes": "Você usou sua habilidade para criar ilusões e distrações, enganando as outras equipes e abrindo caminho."}},
            {"pergunta": "Sua equipe vence! Na cerimônia, vocês recebem a 'Medalha da Bravura'.", "opcoes": {"Agradece ao seu parceiro": "No seu discurso, você fez questão de dizer que a vitória só foi possível graças ao trabalho em equipe e à ajuda do seu parceiro.", "Dedica a vitória à academia": "Você dedicou a medalha a todos os professores e alunos, que te inspiram a ser um herói melhor a cada dia.", "Pensa no próximo desafio": "Com a medalha no peito, sua mente já estava focada no futuro, pensando em como poderia melhorar ainda mais."}},
            {"pergunta": "Um herói famoso visita a academia para dar uma palestra. Ele te chama para uma conversa particular.", "opcoes": {"Pede conselhos": "Você aproveitou a oportunidade para pedir conselhos sobre como lidar com a responsabilidade de ter superpoderes.", "Conta suas aventuras": "Você contou a ele sobre suas experiências na academia, e ele ouviu com um sorriso, orgulhoso da nova geração.", "Pergunta sobre o maior desafio dele": "Você perguntou qual foi a missão mais difícil que ele já enfrentou, buscando aprender com sua experiência."}},
            {"pergunta": "Você descobre que seu poder tem um efeito colateral inesperado e divertido.", "opcoes": {"Velocidade te faz viajar no tempo": "Você descobriu que se correr rápido o suficiente, pode dar pequenos saltos de alguns segundos para o futuro.", "Plantas te dão frutas exóticas": "Às vezes, as plantas que você controla produzem frutas que ninguém nunca viu, com sabores incríveis.", "Invisibilidade te deixa ouvir pensamentos": "Quando você fica invisível por muito tempo, começa a ouvir sussurros dos pensamentos das pessoas ao redor."}},
            {"pergunta": "No final do seu primeiro ano, você é escolhido para ser o líder da sua turma. Qual sua primeira promessa?", "opcoes": {"Promete proteger a todos": "Você prometeu que usaria seus poderes e sua liderança para garantir a segurança e o bem-estar de todos na academia.", "Promete incentivar o trabalho em equipe": "Você discursou sobre a importância da união, prometendo criar mais atividades em grupo para fortalecer os laços.", "Promete que todos vão se divertir": "Você prometeu que, além de treinar para serem grandes heróis, todos teriam tempo para se divertir e serem amigos."}}
        ]
    },
    "viagem_tempo": {
        "titulo": "A Máquina do Tempo do Vovô",
        "icone": "⏳",
        "estagios": [
            {"pergunta": "No porão do seu avô, você encontra uma máquina do tempo! O painel mostra três destinos: qual você escolhe?", "opcoes": {"Era dos Dinossauros": "A paixão por dinossauros falou mais alto e você digitou as coordenadas para o Período Cretáceo.", "Futuro (Ano 2500)": "A curiosidade sobre o futuro te venceu e você ajustou o cronômetro para o distante ano de 2500.", "Antigo Egito": "Fascinado por pirâmides e faraós, você escolheu viajar para o auge da civilização do Antigo Egito."}},
            {"pergunta": "Você chega ao seu destino, mas a máquina faz um barulho estranho e desliga. O que você faz?", "opcoes": {"Tenta um conserto rápido": "Você abriu um painel lateral e, usando sua intuição, tentou reconectar alguns fios que pareciam soltos.", "Explora os arredores": "Você decidiu deixar a máquina de lado por um momento e explorar cuidadosamente a área ao redor para se localizar.", "Camufla a máquina": "Com medo de que alguém a encontrasse, você usou folhas ou areia para esconder a máquina do tempo antes de tudo."}},
            {"pergunta": "Você encontra um habitante local: um dinossauro assustado / um robô curioso / um mercador egípcio. Como você interage?", "opcoes": {"Oferece comida": "Você pegou uma barra de cereal da sua mochila e a ofereceu como um sinal de paz e amizade.", "Tenta se comunicar com gestos": "Usando as mãos e o corpo, você tentou se comunicar de forma universal, mostrando que não era uma ameaça.", "Fica escondido observando": "Com cautela, você se escondeu atrás de uma rocha ou parede, preferindo observar antes de fazer contato."}},
            {"pergunta": "Você descobre que uma peça essencial da máquina do tempo se perdeu durante a viagem.", "opcoes": {"Você tenta criar uma réplica": "Usando os recursos da época, você tentou construir uma versão improvisada da peça que precisava.", "Você procura pela peça original": "Acreditando que a peça deveria ter caído por perto, você refez seus passos para tentar encontrá-la.", "Você busca ajuda local": "Você mostrou um desenho da peça para seu novo amigo local, na esperança de que ele soubesse onde encontrar algo parecido."}},
            {"pergunta": "Seu novo amigo te ajuda na busca. Ele te leva a um lugar perigoso, mas importante.", "opcoes": {"Um ninho de T-Rex": "Ele te levou a um ninho de Tiranossauro, onde a peça brilhava entre os ovos gigantes.", "Um ferro-velho de robôs": "Ele te guiou a um depósito de robôs antigos, onde a peça poderia ser encontrada entre a sucata.", "A oficina de um inventor": "Ele te apresentou a um inventor da corte do faraó, que talvez pudesse recriar a peça para você."}},
            {"pergunta": "Para conseguir a peça, você precisa realizar uma tarefa para o 'dono' do lugar.", "opcoes": {"Recuperar um ovo roubado": "A mãe T-Rex queria que você recuperasse um de seus ovos que havia rolado para uma fenda perigosa.", "Reativar um robô antigo": "O robô-chefe do ferro-velho pediu para você reativar um velho amigo, um robô contador de histórias.", "Resolver um enigma do inventor": "O inventor te desafiou com um enigma de lógica para provar que você era digno de sua ajuda."}},
            {"pergunta": "Você consegue a peça! Ao voltar para a máquina, você percebe que a história mudou um pouco por sua causa.", "opcoes": {"Você deixa um presente": "Como agradecimento, você deixou seu relógio digital para trás, um pequeno objeto que poderia inspirar futuras invenções.", "Você apaga seus rastros": "Preocupado com o paradoxo temporal, você fez o seu melhor para apagar todos os sinais de sua passagem por ali.", "Você tira uma 'selfie'": "Incapaz de resistir, você tirou uma foto rápida com seu novo amigo, um registro de sua incrível aventura."}},
            {"pergunta": "A máquina está consertada. Antes de voltar, seu amigo te dá um presente de despedida.", "opcoes": {"Um dente de dinossauro": "O dinossaurinho te deu um de seus dentes de leite que havia caído, um fóssil único.", "Um chip de memória universal": "O robô te deu um chip que continha toda a história e cultura da sua civilização.", "Um amuleto de proteção": "O egípcio te deu um amuleto sagrado para te proteger em todas as suas futuras jornadas."}},
            {"pergunta": "Você volta para o porão do seu avô, um minuto depois de ter partido. Tudo parece normal.", "opcoes": {"Você abraça seu avô": "A primeira coisa que você fez foi correr e dar um abraço apertado em seu avô, grato por tudo.", "Você guarda o suvenir": "Você escondeu o presente que ganhou em um lugar seguro, um tesouro que prova que sua viagem foi real.", "Você anota tudo no diário": "Você correu para seu quarto e começou a escrever cada detalhe da sua aventura para nunca esquecer."}},
            {"pergunta": "Seu avô te vê e sorri, dizendo 'Espero que tenha se divertido'. O que você percebe?", "opcoes": {"Ele sempre soube": "Você percebeu pelo brilho nos olhos dele que seu avô também era um viajante do tempo e sabia de tudo.", "Ele encontrou uma pista": "Você notou um pouco de areia do Egito perto da máquina e percebeu que seu avô era mais esperto do que parecia.", "Foi tudo um sonho... ou não?": "Você ficou na dúvida se tudo foi real, mas ao tocar no presente em seu bolso, teve a certeza de que viveu uma grande aventura."}}
        ]
    },
    "cidade_submersa": {
        "titulo": "A Cidade Submersa",
        "icone": "🌊",
        "estagios": [
            {"pergunta": "Explorando a praia, você encontra uma garrafa com um mapa que aponta para algo no meio do oceano. O que você faz?", "opcoes": {"Pega o barco do seu tio": "Sem pensar duas vezes, você pegou o pequeno barco de pesca do seu tio e começou a seguir o mapa.", "Mostra para um biólogo marinho": "Você levou o mapa para a bióloga marinha local, que ficou fascinada e se ofereceu para ir junto.", "Usa um drone para investigar": "Você usou seu drone de brinquedo para sobrevoar a área indicada no mapa e ver o que havia lá."}},
            {"pergunta": "O mapa te leva a um redemoinho que, surpreendentemente, é uma passagem para o fundo do mar. Como você entra?", "opcoes": {"Mergulha de cabeça": "Com um fôlego fundo e o coração cheio de coragem, você mergulhou diretamente no centro do redemoinho.", "Usa equipamento de mergulho": "Com o equipamento fornecido pela bióloga, você desceu de forma controlada e segura pela passagem aquática.", "Envia uma câmera primeiro": "Você amarrou uma câmera à prova d'água em uma corda e a desceu para ver o que havia do outro lado."}},
            {"pergunta": "Você chega a uma cidade submersa, protegida por uma bolha de ar gigante. A cidade está silenciosa.", "opcoes": {"Explora a praça central": "Você nadou em direção a uma grande praça no centro da cidade, cheia de estátuas de coral.", "Entra no prédio mais alto": "Sua atenção foi para a torre mais alta, feita de conchas cintilantes, e você decidiu investigar o que havia no topo.", "Segue as luzes piscantes": "Você notou pequenas luzes piscando em uma rua estreita e seguiu o sinal luminoso com curiosidade."}},
            {"pergunta": "Você encontra os habitantes: um povo que respira na água e é muito tímido. Como você se aproxima?", "opcoes": {"Oferece um objeto da superfície": "Você mostrou a eles uma concha que encontrou na praia, um objeto familiar para criar uma conexão.", "Tenta imitar seus sons": "Você ouviu os sons suaves que eles emitiam e tentou imitá-los, mostrando que queria ser amigável.", "Espera eles se aproximarem": "Você ficou parado e sorriu, esperando que a curiosidade deles vencesse a timidez."}},
            {"pergunta": "Eles te contam que a bolha de ar da cidade está enfraquecendo. Eles precisam de ajuda.", "opcoes": {"Você busca a fonte de energia": "Eles te explicaram que a bolha era mantida por uma Pérola Gigante, e você se ofereceu para encontrar uma forma de recarregá-la.", "Você tenta consertar a bolha": "Você notou uma rachadura na 'parede' da bolha e procurou uma forma de selá-la com os recursos locais.", "Você ensina a eles sobre a superfície": "Você pensou que talvez fosse hora de eles conhecerem a superfície e se ofereceu para ser o guia deles."}},
            {"pergunta": "A Pérola Gigante precisa da 'luz do sol do meio-dia' para recarregar. Como você resolve isso?", "opcoes": {"Usa um sistema de espelhos": "Você teve a ideia de criar um sistema de espelhos e objetos brilhantes para refletir a luz do sol da superfície até a pérola.", "Move a pérola para mais perto": "Você ajudou o povo da cidade a mover a pesada pérola para a parte mais rasa da cidade, onde a luz chegava.", "Cria uma lente de aumento": "Usando um pedaço de vidro da sua máscara de mergulho, você criou uma lente para focar a luz do sol na pérola."}},
            {"pergunta": "Com a bolha restaurada, a cidade volta a brilhar e a vibrar com energia. Eles fazem uma festa em sua homenagem.", "opcoes": {"Dança com os habitantes": "Você aprendeu a dança tradicional deles e celebrou junto, girando entre os peixes coloridos.", "Experimenta a comida local": "Você provou as algas doces e as frutas do mar que eles ofereceram, uma culinária única e deliciosa.", "Ouve as histórias dos anciãos": "Você se sentou com os mais velhos e ouviu as incríveis histórias e lendas da cidade submersa."}},
            {"pergunta": "A rainha da cidade te oferece um presente como agradecimento. O que você escolhe?", "opcoes": {"Um tridente que controla a água": "Ela te deu um pequeno tridente que permite controlar pequenas correntes de água, uma ferramenta muito útil.", "Uma pérola que brilha no perigo": "Você recebeu uma pérola que começa a brilhar e aquecer sempre que um perigo se aproxima.", "A habilidade de respirar debaixo d'água": "A rainha te deu uma bênção que permite que você respire debaixo d'água por uma hora, uma vez por dia."}},
            {"pergunta": "É hora de voltar para a superfície. Como você se despede?", "opcoes": {"Promete voltar para visitar": "Você prometeu aos seus novos amigos que voltaria para visitá-los e que nunca esqueceria deles.", "Deixa um mapa para eles": "Você desenhou um mapa da sua cidade na areia, para que eles soubessem de onde você veio.", "Leva uma mensagem deles": "Eles te pediram para levar uma mensagem de paz para o povo da superfície, e você aceitou a missão."}},
            {"pergunta": "De volta à praia, você olha para o oceano de uma forma diferente. Qual sua nova paixão?", "opcoes": {"Tornar-se um oceanógrafo": "Você decidiu que iria estudar os oceanos para proteger seus segredos e os amigos que fez.", "Ser um construtor de pontes": "Você percebeu que sua vocação era conectar mundos diferentes, seja em terra ou no mar.", "Ser um guardião de segredos": "Você entendeu que alguns lugares mágicos devem ser mantidos em segredo, e se tornou seu guardião silencioso."}}
        ]
    },
    "ilha_dos_piratas": {
        "titulo": "A Ilha do Pirata Fantasma",
        "icone": "🏴‍☠️",
        "estagios": [
            {"pergunta": "Você acha um diário de um pirata que fala de um tesouro na Ilha da Caveira. O que mais te chama a atenção no diário?", "opcoes": {"O mapa do tesouro": "Seus olhos brilharam para o mapa detalhado, com um 'X' marcando o local exato do tesouro.", "A história de um fantasma": "Você ficou mais intrigado com a lenda de que o fantasma do pirata ainda guardava o tesouro.", "O desenho de um navio": "O que mais te fascinou foi o desenho do navio do pirata, o 'Vingança Sombria', e suas incríveis velas negras."}},
            {"pergunta": "Você consegue um barco e navega até a ilha. Onde você ancora?", "opcoes": {"Na Baía dos Naufrágios": "Você ancorou em uma baía cheia de navios naufragados, um lugar assustador, mas que parecia esconder segredos.", "Na Enseada das Tartarugas": "Você escolheu uma enseada calma e ensolarada, famosa por ser um santuário de tartarugas marinhas.", "Na Praia do Sussurro": "Você parou em uma praia onde o vento, ao passar pelas rochas, criava um som parecido com sussurros."}},
            {"pergunta": "O mapa diz: 'Siga o olhar do macaco de pedra'. Há três estátuas de macaco. Qual você segue?", "opcoes": {"O que aponta para a selva": "Você seguiu a direção indicada pelo macaco que apontava para a parte mais densa e escura da selva.", "O que olha para a cachoeira": "Você foi na direção da grande cachoeira, imaginando que o tesouro poderia estar escondido atrás dela.", "O que tampa os ouvidos": "Intrigado, você foi na direção oposta ao som, seguindo a lógica do macaco que não queria ouvir algo."}},
            {"pergunta": "Você encontra uma armadilha! Um alçapão se abre sob seus pés. Como você reage?", "opcoes": {"Agarra-se a uma raiz": "Com reflexos rápidos, você se agarrou a uma raiz de árvore na beirada do alçapão, evitando a queda.", "Usa a mochila para amortecer": "Você rapidamente jogou sua mochila no fundo do buraco para amortecer a queda e caiu em segurança.", "Pula para o lado": "Com um salto atlético, você conseguiu pular para o lado no último segundo, escapando da armadilha."}},
            {"pergunta": "Você chega a uma caverna. Dentro, o fantasma do pirata Barba de Fogo aparece! Ele não parece feliz.", "opcoes": {"Você o enfrenta com coragem": "Você pegou um galho de árvore como uma espada e se preparou para um duelo, sem se intimidar com o fantasma.", "Você tenta conversar com ele": "Com calma, você tentou conversar com o fantasma, perguntando por que ele ainda estava ali.", "Você oferece algo a ele": "Você abriu sua mochila e ofereceu a ele sua bússola, dizendo que talvez pudesse ajudá-lo a encontrar seu caminho."}},
            {"pergunta": "O fantasma revela que não quer o tesouro, mas sim encontrar seu papagaio perdido, o Faísca.", "opcoes": {"Você se oferece para ajudar": "Com compaixão, você se ofereceu para ajudar o pirata a encontrar seu amigo de penas perdido.", "Você pergunta como era o papagaio": "Para ajudar na busca, você pediu ao fantasma para descrever o papagaio e seus hábitos.", "Você argumenta que o tesouro é seu": "Você tentou argumentar que o diário te dava o direito ao tesouro, mas o fantasma não cedeu."}},
            {"pergunta": "O pirata te diz que Faísca adorava 'frutas brilhantes'. Você lembra de ter visto algo assim.", "opcoes": {"No topo do vulcão": "Você se lembrou de ter visto frutas que brilhavam com o calor perto da cratera do vulcão adormecido.", "Numa gruta de cristais": "Você se recordou de uma pequena gruta onde a luz se refletia nos cristais e em frutinhas exóticas.", "Perto de vaga-lumes": "Você lembrou de uma clareira onde os vaga-lumes se reuniam à noite, iluminando frutas silvestres."}},
            {"pergunta": "Você encontra o papagaio, que está feliz e saudável. Ele te dá uma chave que carregava no pescoço.", "opcoes": {"Você leva o papagaio ao pirata": "Você levou o papagaio de volta para o fantasma, que chorou de alegria ao reencontrar seu amigo.", "Você atrai o pirata até o papagaio": "Você imitou o som do papagaio, e o fantasma te seguiu, curioso, até o local do reencontro.", "Você pede para o papagaio te guiar": "Você mostrou a chave ao papagaio, que entendeu e voou na direção do baú do tesouro."}},
            {"pergunta": "O fantasma, feliz, te diz que o tesouro é seu. O baú está cheio de moedas de ouro e joias.", "opcoes": {"Você divide o tesouro": "Você insistiu em dividir o tesouro com o fantasma, mas ele disse que sua única riqueza era sua amizade.", "Você pega apenas uma moeda": "Como lembrança, você pegou apenas uma única moeda de ouro, deixando o resto para a história.", "Você decide criar um museu": "Você decidiu usar o tesouro para criar um museu na ilha, contando a história do pirata e seu papagaio."}},
            {"pergunta": "Com o fantasma finalmente em paz, ele e seu papagaio desaparecem em um brilho dourado. O que você faz?", "opcoes": {"Volta para casa como uma lenda": "Você voltou para casa e sua história se tornou uma lenda, inspirando novos aventureiros.", "Fica na ilha como protetor": "Você decidiu ficar na ilha, tornando-se o guardião de seus segredos e de sua magia.", "Usa o tesouro para explorar o mundo": "Com os recursos que encontrou, você comprou seu próprio navio para explorar outros mistérios do mundo."}}
        ]
    },
    "circo_magico": {
        "titulo": "O Circo da Lua Cheia",
        "icone": "🎪",
        "estagios": [
            {"pergunta": "Um circo misterioso chega na sua cidade, abrindo apenas em noites de lua cheia. Você decide ir. Qual atração você vê primeiro?", "opcoes": {"O mágico ilusionista": "Você foi para a tenda do mágico, famoso por fazer truques que pareciam ser magia de verdade.", "Os trapezistas voadores": "Seu olhar se voltou para o alto, onde os trapezistas pareciam voar de um lado para o outro sem rede.", "O palhaço que chora glitter": "Você ficou curioso com o palhaço melancólico, que, em vez de lágrimas, chorava um pó de glitter colorido."}},
            {"pergunta": "Após o show, você encontra um objeto perdido no chão. O que é?", "opcoes": {"A varinha do mágico": "Você encontrou a varinha do mágico, que ainda pulsava com uma energia estranha ao toque.", "Uma luva de trapezista": "Era uma luva de seda, tão leve que parecia ter sido feita com fios de nuvem.", "Um lenço de glitter": "Você pegou o lenço do palhaço, que nunca parava de soltar um brilho sutil e mágico."}},
            {"pergunta": "Você vai devolver o objeto e acaba entrando na área dos bastidores. O que você descobre?", "opcoes": {"A magia é real": "Você vê o mágico praticando, e ele realmente está levitando objetos com a mente, sem truques.", "Os artistas são seres mágicos": "Você vê os trapezistas guardando suas asas de fada e o palhaço conversando com um gnomo.", "O circo viaja entre mundos": "Você vê o dono do circo girando um globo terrestre que mostrava mapas de mundos fantásticos."}},
            {"pergunta": "O dono do circo, um homem simpático chamado Sr. Serebino, te encontra. Qual sua reação?", "opcoes": {"Devolve o objeto e pede desculpas": "Você rapidamente devolveu o objeto, pedindo desculpas por ter entrado onde não devia.", "Faz muitas perguntas": "Maravilhado, você começou a fazer um monte de perguntas sobre a magia e os artistas.", "Pede para se juntar ao circo": "Sem hesitar, você pediu para se juntar à trupe, oferecendo-se para aprender qualquer ofício."}},
            {"pergunta": "Sr. Serebino diz que você tem um talento mágico escondido e se oferece para te ajudar a descobri-lo.", "opcoes": {"Você aceita na hora": "Com o coração pulando de alegria, você aceitou a oferta, ansioso para descobrir seu poder.", "Você fica desconfiado": "Você ficou um pouco com o pé atrás, perguntando o que ele queria em troca da ajuda.", "Você pede um tempo para pensar": "Você disse que era muita coisa para processar e que precisava de uma noite para pensar no assunto."}},
            {"pergunta": "Seu teste é fazer o público rir. Como você tenta fazer isso?", "opcoes": {"Contando uma piada": "Você subiu no palco e contou a piada mais engraçada que conhecia, e seu talento era o de ter um timing cômico perfeito.", "Fazendo uma acrobacia": "Você tentou dar uma cambalhota, mas tropeçou de um jeito tão engraçado que a plateia inteira gargalhou.", "Com mímica": "Você começou a imitar os outros artistas do circo, e seu dom era o de ser um imitador de primeira."}},
            {"pergunta": "Você descobre que seu talento é 'manipular a alegria'. As pessoas se sentem felizes perto de você.", "opcoes": {"Você ajuda o palhaço triste": "Você usou seu novo poder para ajudar o palhaço a encontrar sua própria alegria, e ele passou a rir de verdade.", "Você energiza os shows": "Sua presença nos bastidores fazia com que todos os shows fossem mais vibrantes e mágicos para o público.", "Você cria um novo número": "Você criou um número onde sua única tarefa era andar pela plateia, espalhando felicidade contagiante."}},
            {"pergunta": "Um inspetor ranzinza tenta fechar o circo. Você precisa usar seu poder para mudar o humor dele.", "opcoes": {"Você oferece a ele um algodão-doce": "Você deu a ele o algodão-doce mais colorido, e ao provar, ele abriu um sorriso pela primeira vez em anos.", "Você o convida para o palco": "Você o chamou para participar de um número, e a alegria do público o contagiou, fazendo-o mudar de ideia.", "Você conta a ele um segredo": "Você sussurrou no ouvido dele um segredo sobre a magia da felicidade, e o coração dele se amoleceu."}},
            {"pergunta": "O circo é salvo! Sr. Serebino te oferece um lugar permanente na trupe.", "opcoes": {"Você aceita e viaja com eles": "Você aceitou e se juntou ao Circo da Lua Cheia, viajando para mundos mágicos e espalhando alegria.", "Você agradece, mas decide ficar": "Você decidiu que seu lugar era em casa, mas que usaria seu dom para alegrar sua própria cidade.", "Você pede para ser um 'agente'": "Você se tornou um 'agente' do circo, responsável por encontrar outros jovens com talentos escondidos no mundo."}},
            {"pergunta": "Antes de partir (ou ficar), você ganha um presente do circo. O que é?", "opcoes": {"Um ingresso dourado vitalício": "Um ingresso que te permite entrar em qualquer espetáculo do circo, em qualquer mundo, para sempre.", "Uma pequena nuvem de algodão-doce": "Uma nuvem que flutua sobre sua cabeça e produz o algodão-doce mais delicioso sempre que você está triste.", "Uma caixa de música mágica": "Uma caixinha de música que, ao tocar, preenche qualquer ambiente com a atmosfera mágica e feliz do circo."}}
        ]
    }
}
